# Generated by Django 3.2.12 on 2023-09-10 15:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('location', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'image_table',
                'managed': False,
            },
        ),
    ]
